// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/RandithaK/StudyBuddy_Backend/internal/models"
)

type AuthPayload struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type ChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type ChangePasswordPayload struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewCourseInput struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

type NewEventInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	CourseID    *string `json:"courseId,omitempty"`
	Date        string  `json:"date"`
	StartTime   string  `json:"startTime"`
	EndTime     string  `json:"endTime"`
	Type        string  `json:"type"`
}

type NewTaskInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CourseID    string `json:"courseId"`
	DueDate     string `json:"dueDate"`
	DueTime     string `json:"dueTime"`
	HasReminder bool   `json:"hasReminder"`
}

type Query struct {
}

type Notification struct {
	ID          string `json:"id"`
	UserID      string `json:"userId"`
	Message     string `json:"message"`
	Type        string `json:"type"`
	ReferenceID string `json:"referenceId"`
	Read        bool   `json:"read"`
	CreatedAt   string `json:"createdAt"`
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateTaskInput struct {
	ID          string  `json:"id"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	CourseID    *string `json:"courseId,omitempty"`
	DueDate     *string `json:"dueDate,omitempty"`
	DueTime     *string `json:"dueTime,omitempty"`
	Completed   *bool   `json:"completed,omitempty"`
	HasReminder *bool   `json:"hasReminder,omitempty"`
	CompletedAt *string `json:"completedAt,omitempty"`
}

type UpdateUserInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}
