// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/RandithaK/StudyBuddy/backend/internal/models"
)

type AuthPayload struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewCourseInput struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

type NewEventInput struct {
	Title     string `json:"title"`
	CourseID  string `json:"courseId"`
	Date      string `json:"date"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
	Type      string `json:"type"`
}

type NewTaskInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CourseID    string `json:"courseId"`
	DueDate     string `json:"dueDate"`
	DueTime     string `json:"dueTime"`
	HasReminder bool   `json:"hasReminder"`
}

type Query struct {
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateTaskInput struct {
	ID          string  `json:"id"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	CourseID    *string `json:"courseId,omitempty"`
	DueDate     *string `json:"dueDate,omitempty"`
	DueTime     *string `json:"dueTime,omitempty"`
	Completed   *bool   `json:"completed,omitempty"`
	HasReminder *bool   `json:"hasReminder,omitempty"`
}
